name = "buildapps-chatbot"
compatibility_date = "2026-03-22"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "bruna-buildapps"
database_id = "b7504904-63dd-4048-8454-1a6e562c9184"