name = "buildapps-chatbot"
compatibility_date = "2026-03-22"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "bruna-buildapps"
database_id = "6fc6f3e5-248a-449b-93eb-266a0dfdadc6"